volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: stesha28/foodgram_backend:latest
    container_name: foodgram_backend
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: stesha28/foodgram_frontend:latest
    container_name: foodgram-front
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: stesha28/foodgram_gateway:latest
    container_name: foodgram-gateway
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/etc/nginx/html/media/
    ports:
      - 8000:80
    depends_on:
      - backend
